spring.application.name=fawazer
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5132/fawazer
spring.datasource.username=fawazer-masry
spring.datasource.password=Masry2212
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
